### ISSUE TITLE
DNS issue

### ISSUE THREAD

**Issue by adulau** [adulau/hashlookup-server#9]
~~~~
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nserver/server.py", line 137, in run
    server.send_message_response(message)
  File "/usr/local/lib/python3.8/dist-packages/nserver/transport.py", line 122, in send_message_response
    self.socket.sendto(data, message.remote_address)
OSError: [Errno 22] Invalid argument
[2022-04-17 19:13:49,638][INFO][nserver.i.dns.hashlookup.circl.lu] Question: ANY sl
[2022-04-17 19:13:49,638][INFO][nserver.i.dns.hashlookup.circl.lu] Did not match any rule
[2022-04-17 19:13:49,638][ERROR][nserver.i.dns.hashlookup.circl.lu] Uncaught error occured. [Errno 22] Invalid argument
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nserver/server.py", line 137, in run
    server.send_message_response(message)
  File "/usr/local/lib/python3.8/dist-packages/nserver/transport.py", line 122, in send_message_response
    self.socket.sendto(data, message.remote_address)
OSError: [Errno 22] Invalid argument
[2022-04-17 19:14:02,905][INFO][nserver.i.dns.hashlookup.circl.lu] Question: ANY sl
[2022-04-17 19:14:02,905][INFO][nserver.i.dns.hashlookup.circl.lu] Did not match any rule
[2022-04-17 19:14:02,905][ERROR][nserver.i.dns.hashlookup.circl.lu] Uncaught error occured. [Errno 22] Invalid argument
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nserver/server.py", line 137, in run
    server.send_message_response(message)
  File "/usr/local/lib/python3.8/dist-packages/nserver/transport.py", line 122, in send_message_response
    self.socket.sendto(data, message.remote_address)
OSError: [Errno 22] Invalid argument
[2022-04-17 19:14:03,246][INFO][nserver.i.dns.hashlookup.circl.lu] Question: ANY sl
[2022-04-17 19:14:03,246][INFO][nserver.i.dns.hashlookup.circl.lu] Did not match any rule
[2022-04-17 19:14:03,246][ERROR][nserver.i.dns.hashlookup.circl.lu] Uncaught error occured. [Errno 22] Invalid argument
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nserver/server.py", line 137, in run
    server.send_message_response(message)
  File "/usr/local/lib/python3.8/dist-packages/nserver/transport.py", line 122, in send_message_response
    self.socket.sendto(data, message.remote_address)
OSError: [Errno 22] Invalid argument
[2022-04-17 19:14:04,276][INFO][nserver.i.dns.hashlookup.circl.lu] Question: ANY sl
[2022-04-17 19:14:04,276][INFO][nserver.i.dns.hashlookup.circl.lu] Did not match any rule
[2022-04-17 19:14:04,276][ERROR][nserver.i.dns.hashlookup.circl.lu] Uncaught error occured. [Errno 22] Invalid argument
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nserver/server.py", line 137, in run
    server.send_message_response(message)
  File "/usr/local/lib/python3.8/dist-packages/nserver/transport.py", line 122, in send_message_response
    self.socket.sendto(data, message.remote_address)
OSError: [Errno 22] Invalid argument
[2022-04-17 19:14:04,276][CRITICAL][nserver.i.dns.hashlookup.circl.lu] Max errors hit (5)
[2022-04-17 19:14:04,276][INFO][nserver.i.dns.hashlookup.circl.lu] Shutting down server
~~~~

**Comment by adulau** [comment]
Fixed in v1.3
